# Generated by Django 5.1.4 on 2024-12-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Employee", "Employee"),
                ],
                default="Employee",
                max_length=50,
            ),
        ),
    ]
