# Generated by Django 5.1.4 on 2024-12-08 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="num_departments",
        ),
        migrations.RemoveField(
            model_name="company",
            name="num_employees",
        ),
        migrations.RemoveField(
            model_name="department",
            name="num_employees",
        ),
    ]
